/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(descramble_dsss_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6c00cd0cbf9a4325bb8d36d85792e059)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dsss/descramble_dsss_bb.h>
// pydoc.h is automatically generated in the build directory
#include <descramble_dsss_bb_pydoc.h>

void bind_descramble_dsss_bb(py::module& m)
{

    using descramble_dsss_bb    = gr::dsss::descramble_dsss_bb;


    py::class_<descramble_dsss_bb, gr::block, gr::basic_block,
        std::shared_ptr<descramble_dsss_bb>>(m, "descramble_dsss_bb", D(descramble_dsss_bb))

        .def(py::init(&descramble_dsss_bb::make),
           D(descramble_dsss_bb,make)
        )
        



        ;




}








